version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'dev_password_!2024'
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "127.0.0.1", "-U", "sa", "-P", "dev_password_!2024", "-Q", "SELECT 1", "-b", "-C"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 30s

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.77.3
    container_name: artifactory
    restart: always
    environment:
      - JF_ROUTER_ENTRY_POINTS_EXTERNAL_URL=http://localhost:8081      
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/artifactory/api/system/ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000

  backend:
    build: ./backend
    environment:
      MS_USER: sa
      MS_PASSWORD: dev_password_!2024
      MS_DB: app_db
      MS_HOST: db
      MS_PORT: 1433
      ARTIFACTORY_BASE_URL: http://localhost:8081/artifactory
      ARTIFACTORY_USERNAME: admin
      ARTIFACTORY_PASSWORD: jq11Art129#@
      ARTIFACTORY_DEFAULT_REPO: generic-local
      PORT: 4000      
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mssql_data:
  artifactory_data: