version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'dev_password_!2024'
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.77.3
    container_name: artifactory
    restart: always
    environment:
      - JF_ROUTER_ENTRY_POINTS_EXTERNAL_URL=http://localhost:8081
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/artifactory/api/system/ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000

  backend:
    build: ./backend
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: very_strong_password
      POSTGRES_DB: app_db
      POSTGRES_HOST: postgres_db
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  mssql_data:
  artifactory_data:
